name: Conventional Commit

on:
  pull_request:
    types:
      - edited
      - opened

permissions:
  pull-requests: read

jobs:
  conventional-commit:
    name: Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Conventional Commit title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: | # mirrors changelog-sections in the /release-please-config.json
            feat
            fix
            infra
            ci
            docs
            deps
            perf
            refactor
            test
            chore
